"""0.1 models are created

Revision ID: bdbe6b8175a0
Revises: 
Create Date: 2025-01-26 21:44:55.007073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbe6b8175a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_login'), ['login'], unique=True)

    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_telegram_id'), ['telegram_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_partners_user_id'), ['user_id'], unique=True)

    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('panel_login', sa.String(), nullable=False),
    sa.Column('panel_password_hash', sa.String(length=256), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_servers_partner_id'), ['partner_id'], unique=False)

    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=False),
    sa.Column('payed', sa.Boolean(), nullable=False),
    sa.Column('payed_date', sa.DateTime(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keys_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_keys_payed_date'), ['payed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_keys_server_id'), ['server_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keys_server_id'))
        batch_op.drop_index(batch_op.f('ix_keys_payed_date'))
        batch_op.drop_index(batch_op.f('ix_keys_created'))

    op.drop_table('keys')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_partner_id'))
        batch_op.drop_index(batch_op.f('ix_servers_name'))

    op.drop_table('servers')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_user_id'))
        batch_op.drop_index(batch_op.f('ix_partners_telegram_id'))

    op.drop_table('partners')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_login'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
